language: r
warnings_are_errors: true

cache: packages

sudo: required

addons:
    apt:
        config:
            retries: true
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
        packages:
            - libssh-dev

r_github_packages:
  - jimhester/covr
  - frehbach/ideaBatch

after_success:
  - Rscript -e 'library(covr);codecov()'
